### ISSUE TITLE
Add device #5740 "ANO rotary navigation encoder"

### ISSUE THREAD

**Issue by danjl1100** [alexeden/adafruit-seesaw#3]
Would you accept a PR adding [Adafruit product #5740](https://www.adafruit.com/product/5740) ("ANO rotary navigation encoder") to the `device` module?

I just picked up a couple of these ANO rotary navigation encoders, and I'm not finding a Rust crate that will easily interface with it.
On a cursory glance, it looks like this crate (with its `seesaw_device!` macro) would be a good fit for it.

I'm thinking I'd try reusing the existing `EncoderModule` logic with the "button" being the center button.  And then follow along with Adafruit's CircuitPython example below to add the 4 extra digital inputs for the up/down/left/right buttons:

https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/89daaec507fa2f5fa4bd7aa9bedf7e8eae09ac44/examples/seesaw_ano_rotary_simpletest.py#L20-L41

Also, if you have any tips or concerns up front, please let me know!

Edit: I just now saw the [Creating Your Own Devices](https://github.com/alexeden/adafruit-seesaw#creating-your-own-devices) part of the readme... whoops, somehow thought it only supported the devices defined internally.

**Comment by danjl1100** [comment]
Please see the PR #4 to re-enable use of the `seesaw_device!` macro by downstream users.

**Comment by alexeden** [comment]
@danjl1100 thank you! Changes are included in [0.5.3.](https://github.com/alexeden/adafruit-seesaw/releases/tag/0.5.3)
